version: '3.8'

services:
  frontend:
    image: opple/worklenz-frontend:20241108
    build:
      context: ./worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz_frontend
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_started
    networks:
      - worklenz    

  backend:
    image: opple/worklenz-backend:20241108
    build:
      context: ./worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz_backend
    ports:
      - "3000:3000"
    environment:
      - ANGULAR_DIST_DIR
      - ANGULAR_SRC_DIR
      - AWS_REGION
      - BACKEND_PUBLIC_DIR
      - BACKEND_VIEWS_DIR
      - COMMIT_BUILD_IMMEDIATELY
      - COOKIE_SECRET
      - DB_HOST=10.1.5.177
      - DB_MAX_CLIENTS
      - DB_NAME=worklenz_db
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_USER=worklenz_backend
      - GOOGLE_CALLBACK_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - HOSTNAME
      - LOGIN_FAILURE_REDIRECT
      - NODE_ENV
      - PORT
      - SESSION_NAME
      - SESSION_SECRET
      - SLACK_WEBHOOK
      - SOCKET_IO_CORS
      - SOURCE_EMAIL
      - USE_PG_NATIVE
      - BUCKET
      - REGION
      - S3_URL
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
    networks:
      - worklenz  

networks:
  worklenz:
    driver: bridge
